### ISSUE TITLE
High CPU usage for CAKE-autorate.sh

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#17]
I'm starting a new issue from #16 that began life as a trouble report, but morphed into observations about performance.

At @lynxthecat suggestion, I adjusted `defaults.sh` to slow the ping rate using:

```
ping_reflector_interval=0.2 # (milliseconds)
main_loop_tick_duration=1000 # (milliseconds)
```
It did improve the utilization: Here's a video of `htop` while idle, then under load, and then recovering from the load. https://youtu.be/pUZ7MpN85K4

PS I can't really tell whether this code addresses latency. I have a fixed speed fiber link through my ISP at 25/25 mbps, so my link speed doesn't vary much. So I just cannot say whether it makes a difference.

**Comment by lynxthecat** [comment]
@dim-geo any thoughts about possible performance optimisations in this bash implementation (my most sophisticated yet). This gives best performance for me out of all branches on my LTE connection. 

I'm asking you because you pushed those awk enhancements to the original shell script. 

The main processing aspects of this approach are in the main loop inside 'CAKE-autorate.sh' and the tail loop inside 'monitor_reflector_path.sh'.

**Comment by richb-hanover** [comment]
I ask the same question as I asked about the Lua implementation: [Where's the Storage?](https://github.com/sqm-autorate/sqm-autorate/issues/147)

That is, I observe that CPU utilization and load average jump up after a burst of traffic, but that they decay gradually back to a baseline over a minute or more. 

Why is that? I would have expected that the utilization/load average would drop back to baseline instantly, or at worst, within a second after the traffic ceases.

What keeps the load average high for a period of time? Where does the "work" come from? Are there ping packets queued up in the network stack (or - Horrors - in buffers?) that take time to "work off"? Is there some other processing that gets deferred? 

Note: This may be a different question from "optimizing the code". (Hypothetical example) If the code queues three packets per second, but only processes one packet per second, even infinitely fast code won't solve that problem.

Thanks.

**Comment by lynxthecat** [comment]
The video you sent still shows very high CPU utilisation does it not? I mean it seems to show CPU @ 100%. Is that related to the bash script processes? I can't see the percentage occupied by the bash script processes.

The bash implementation should equate to more processing on higher load. In terms of its mechanics for each reflector it sets up a ping process with interval ping_reflector_interval that outputs to a file, and that file is read in with a 'tail -f', and each incoming ping result is processed and then that file reset, and there is a main loop that runs every 'main_loop_tick_duration' and checks to see the load and how many reflectors are delayed to decide how to change the CAKE bandwidth. 

So there isn't actually all that much processing going on. I suspect the 'tail -f' aspect could be optimized somehow, but that would seem to require advanced knowledge of how bash works with pipe buffers etc. The use of 'tail -f' and resetting the file is a hack to avoid the processing of ping results lagging behind the incoming ping results or a file to grow infinitely. 

As a thought experiment, imagine:

`ping -i 0.1 1.1.1.1 | while read ping_line do; echo $ping_line; sleep 1; done`

The processing on the right is slower than the processing on the left, so the output will lag behind. I wanted to avoid this, hence I set up ping to output to a file, and the file read in with 'tail -f' and reset after each read in, to ensure the processing does not lag behind and file does not grow. This is a hack, and perhaps that can be optimized.

**Comment by richb-hanover** [comment]
> The processing on the right is slower than the processing on the left, so the output will lag behind. I wanted to avoid this, hence I set up ping to output to a file, and the file read in with 'tail -f' and reset after each read in, to ensure the processing does not lag behind and file does not grow. This is a hack, and perhaps that can be optimized.

I'm glad to see you have thought this. That's the kind of thing I was suggesting...

**Comment by Marctraider** [comment]
Not sure if it matters, but the router in question that I have is an Intel NUC with Intel(R) Celeron(R) J4005 CPU 2.6Ghz (Turbo)
It must be noted though that it runs on 2.6GHz all the time, most power saving disabled. Not sure if that skews results.

Idle:
![image](https://user-images.githubusercontent.com/29001732/157053069-06a25d1c-2768-4ca8-bcb9-2984fb4d916c.png)

Max Load:
![image](https://user-images.githubusercontent.com/29001732/157053342-0a21d29c-82aa-4455-ae74-68ac8f34cbd7.png)

I see the cpu usage is indeed quite high on load for the script, but personally not too worried as I still have some breathing room and the router has no other function.

Still, could defo see optimization.

**Comment by Marctraider** [comment]
I manually assign interrupts and process affinities usually, (either through taskset or through CPUAffinity variable in systemd files.

I actually thing the OP is right:

![image](https://user-images.githubusercontent.com/29001732/157066301-cfa430b9-3a38-4b48-b1e3-b7e2ff59b83a.png)

There's so much CPU usage it overflows to the second core (basically 1.5x load on my 2 cores) which i also problematic for me as on full load, the userspace app dealing with the redundant connection also almost fully saturating a full core.

It keeps going so far minutes after the openspeedtest.net was ran. (Im also not getting good results while running this test).

Strange, it has already been running for a day now with systemd so lets see what happens when i restart the service and check its behavior.

**Comment by lynxthecat** [comment]
Does this test script eat up CPU cycles on your system:

`#!/bin/bash

ping -i 0.1 1.1.1.1 > /tmp/ping_output&

tail -f /tmp/ping_output | while read ping_line

do

        echo $ping_line

        > /tmp/ping_output

done`

**Comment by Marctraider** [comment]
At first glance, basically nothing to 1%~ average, but now I run it for 30 or more seconds I start to see the cpu usage of the script climbing up gradually. (Now at 7%). If this keeps up I can only conclude it will eventually max out and start to slow down because of no more cpu cycles left.

**Comment by lynxthecat** [comment]
Ah great. We have a possible reason for the error now. So just to confirm the simple ping/tail test script results in increased cpu usage with time? This is very revealing.

**Comment by richb-hanover** [comment]
Sorry - I only answered some of your questions. And I realize there are new messages since I wrote this (and forgot to press Submit...) I'll look at the new questions later today.

> The video you sent still shows very high CPU utilisation does it not? I mean it seems to show CPU @ 100%. Is that related to the bash script processes? I can't see the percentage occupied by the bash script processes.

* Yes - I suspect about half of the CPU usage is the bash scripts. 

   - On an idle router, with no CAKE-autorate running, I see 2-5% CPU, near-zero load average. 
   - When I  run the netperf test alone (betterspeedtest.sh) without CAKE-autorate, I see 40-50% CPU use, negligible load average (< 0.05) . 
   - Running the bash script alone (no file transfers) uses 50-60% of the CPU, load average creeping above 2.0 to stay between 2.0 & 3.0
   - Running speedtest.sh causes CPU to hit 100% most of the time with load average getting above 2.0 or 3.0.

* I note that there are nine (9) CAKE-autorate.sh instances running. Is this expected?

```
root@LBWO-C7v2:~# top -b -n 1 | head -20
Mem: 54388K used, 69004K free, 1212K shrd, 4504K buff, 15484K cached
CPU:  50% usr  50% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 1.74 0.65 0.23 1/72 10465
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
19511 19483 root     S     2060   2%  17% bash ./CAKE-autorate.sh
19438 19416 root     S     2060   2%  17% bash ./CAKE-autorate.sh
 1580     1 root     S     4376   4%   0% /usr/sbin/hostapd -s -g /var/run/hostapd/global
 1581     1 root     S     4280   3%   0% /usr/sbin/wpa_supplicant -n -s -g /var/run/wpa_supplicant/global
 2071     1 root     S     4096   3%   0% /usr/sbin/uhttpd -f -h /www -r LBWO-C7v2 -x /cgi-bin -u /ubus -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -R -p 0.0.0.0:80 -p [::]:80 -C /etc/uhttpd.crt -K /etc/uhttpd.key -s 0.0.0.0:443 -s [::]:443
 1274     1 root     S     2316   2%   0% /sbin/rpcd -s /var/run/ubus/ubus.sock -t 30
19344 26560 root     S     2080   2%   0% bash ./CAKE-autorate.sh
19357 19347 root     S     2060   2%   0% bash ./CAKE-autorate.sh
19382 19369 root     S     2060   2%   0% bash ./CAKE-autorate.sh
10465 19511 root     R     2060   2%   0% [bash]
19416 19344 root     S     2056   2%   0% bash ./CAKE-autorate.sh
19483 19344 root     S     2056   2%   0% bash ./CAKE-autorate.sh
19369 19344 root     S     2052   2%   0% bash ./CAKE-autorate.sh
19347 19344 root     S     2052   2%   0% bash ./CAKE-autorate.sh
 1643     1 root     S     1800   1%   0% /sbin/netifd
    1     0 root     S     1632   1%   0% /sbin/procd
```
* Also, I'm still using the following settings to minimize the CPU

```
ping_reflector_interval=0.1 # (milliseconds)
main_loop_tick_duration=200 # (milliseconds)
```

**Comment by Marctraider** [comment]
> So just to confirm the simple ping/tail test script results in increased cpu usage with time? This is very revealing.

Confirmed.

You mean as in so?:

```
#!/bin/bash

ping -i 0.1 10.0.0.1 > /tmp/ping_output&

tail -f /tmp/ping_output | while read ping_line

do

        echo $ping_line

        echo "" > /tmp/ping_output

done

```

**Comment by lynxthecat** [comment]
Yes @Marctraider exactly - there are a bunch of child processes created to multiple entries are expected. I am shocked by even just:

```
#!/bin/bash

ping -i 0.1 10.0.0.1 > /tmp/ping_output&

tail -f /tmp/ping_output | while read ping_line

do

        echo $ping_line

        echo "" > /tmp/ping_output

done
```

Resulting in a CPU spike with time. If that does, then the script will also. 

Can you confirm that removing the 'echo' line results in CPU usage maintaining very low? If so, the question is how to deal with the reset / file growth problem in a way that does not result in increased CPU usage with time.

**Comment by Marctraider** [comment]
> Yes @Marctraider exactly - there are a bunch of child processes created so multiple entries are expected. I am shocked by even just:
> 
> ```
> #!/bin/bash
> 
> ping -i 0.1 10.0.0.1 > /tmp/ping_output&
> 
> tail -f /tmp/ping_output | while read ping_line
> do
>         echo $ping_line
>         echo "" > /tmp/ping_output
> done
> ```
> 
> Resulting in a CPU spike with time. If that does, then the script will also.
> 
> Can you confirm that removing the 'echo' line results in CPU usage maintaining very low? If so, the question is how to deal with the reset / file growth problem in a way that does not result in increased CPU usage with time.

#echo "" > /tmp/ping_output

Results in no growing cpu usage, and very little (0.3%~)

**Comment by Marctraider** [comment]
Hrm.. I will try and think with you on this, but I'm not the best when it comes to scripting .__.

Ideally you'd want to fetch as much possible pings without just randomly skipping when not necessary or you'll lose valuable data points.

Not entirely related to this, but assuming cpu usage is fixed; Is it possible to have even lower than .1 (100ms) of ping intervals with regular ping? Or is that the limit?

**Comment by lynxthecat** [comment]
Even lower is possible. And since you have your own server, you can go as low as you like without worrying about getting into trouble.

**Comment by Marctraider** [comment]
> Even lower is possible. And since you have your own server, you can go as low as you like without worrying about getting into trouble.

Yea certainly. I just recall some ping utilities where 0.1 was the max iirc. But i could be mistaken.

So you are saying that basically pings stack up faster than the script can handle, thus starting to buffer and buffer with more cpu usage as result?

**Comment by lynxthecat** [comment]
No it's just I am simulating the problem. 

```
#!/bin/bash

ping -i 0.1 1.1.1.1 | while read ping_line
do
        echo $ping_line
        sleep 1
done
```

The sleep 1 is just to simulate a delay in processing the incoming pings. We somehow need to skip to the latest ping available, if that makes sense? 

I hacked around this by resetting the file within 'tail -f', but this appears to give rise to high CPU usage for some reason I do not understand.

**Comment by lynxthecat** [comment]
I think I've solved it with:

```
#!/bin/bash

file=/tmp/test

ping -i 0.1 1.1.1.1 | while read line; do echo $line > $file; done&
sleep 1

while true
do
        cat $file
        sleep 1
done
```

**Comment by Marctraider** [comment]
> No it's just I am simulating the problem.
> 
> ```
> #!/bin/bash
> 
> ping -i 0.1 1.1.1.1 | while read ping_line
> do
>         echo $ping_line
>         sleep 1
> done
> ```
> 
> The sleep 1 is just to simulate a delay in processing the incoming pings. We somehow need to skip to the latest ping available, if that makes sense? Such that we only echo the latest available ping each time. Naturally so long as the processing is fast enough then we don't need to skip any pings, but we do need to manage the situation in case of CPU spikes.
> 
> I hacked around this by resetting the file within 'tail -f', but this appears to give rise to high CPU usage for some reason I do not understand.

Possible to clear the file with another command instead?

**Comment by lynxthecat** [comment]
That's what I tried with the echo "" > but you said the cpu issue remained. Maybe we can try something else?

**Comment by richb-hanover** [comment]
I'd like to look back to a comment from @Marctraider 

> Not entirely related to this, but assuming cpu usage is fixed; Is it possible to have even lower than .1 (100ms) of ping intervals with regular ping? Or is that the limit?

As we continue our research, I hope we explore the other direction: _how slowly can we send those pings while still maintaining good latency and speed control?_ Finding a good lower limit to the ping rate would have these advantages:

- It obviously uses less CPU
- It avoids the "tragedy of the commons", where one person pinging those well-known hosts works really for them; ten million CAKE-autorate people (generating 100 million pings/second) would be a tragedy.

Do we have any information about how rapidly/how much LTE or Cable Modem speeds vary in real life? Maybe we could collect it ourselves...

We could collect long-term data (over the course of hours? maybe even days?) that record how often the CAKE-autorate algorithm needs to adjust the parameters, and the effect those changes made on latency (or the effect on latency, had those changes not been made...)

**Comment by Marctraider** [comment]
I think it is almost directly related to how fast your ping interval is truthfully, since the scripts ability to react to bufferbloat is completely dependent on ICMP response back and forth. The smaller the interval between pings the faster you can act on that first big bufferbloat 'spike'.

What would be the reason that a 0.1 is even troublesome, I bet our CPU's (Well, most of them) can handle 100's of pings a second without much trouble. And payload can be kept to a minimum as well to keep bandwidth in check.

**Comment by lynxthecat** [comment]
I think perhaps the solution may be something along these lines:

```
#!/bin/bash

pipe=/tmp/test
mkfifo $pipe

ping -i 0.1 1.1.1.1 > $pipe&
sleep 1

while read ping_line <$pipe
do
        echo $ping_line

        dd if=$pipe iflag=nonblock of=/dev/null
done
```

But that does not work. I can't work out how to 'reset' the fifo buffer.

**Comment by moeller0** [comment]
> As we continue our research, I hope we explore the other direction: _how slowly can we send those pings while still maintaining good latency and speed control?

There are two issues at play here:
1) ping rate in not overwhelming reflectors, I think we can solve that by interleaving pining of multiple reflectors this will allow to keep the individual reflector rate low.
2) delay in getting new delay estimates and hence delay in detecting and responding to congestion.

As a data point, normal unix ping will allow intervals down to 0.2 seconds for non-root users while defaulting to 1 second intervals; that indicates to me that per-reflector rate somewhere between 0.2-5Hz (5 to 0.2 second interval) might be acceptable if we select from a sufficiently large set of reflectors. (Or better yet, operate our own reflectors at which point higher rates are an option, and here I mean that each user of autorate will operate her/his own VPS reflector).

For 2 I initially thought once per second would be enough, but @lynxthecat's access link demonstrates that might be a bit coarse and results in relative long delay spikes... Getting this down to 0.1 seconds seems feasible to me.



> * It avoids the "tragedy of the commons",

I do not think that tragedy actually exists... IMHO this is just a way to dress up "insufficiently strict rule enforcement" in terms that make it appear something else then regulatory failure, often pushed by parties that have vested interest in seeing regulation fail, but I digress. Your point stands though, if the reflectors encounter too high load I expect them to rate-limit/de-prioritize ICMP packets (basically enforcing their rules, so not regulatory failure) the autorate code needs to expect and react to that in a considerate way (changing reflectors and giving the unhappy reflector time to col-off).



> Do we have any information about how rapidly/how much LTE or Cable Modem speeds vary in real life? Maybe we could collect it ourselves...

I think to do that one would need to continuously saturate the link for a considerable amount of time and measure the packets traversing the link.... just looking at how often the code triggers will not give the "veridical" rate-changes of the link.

**Comment by lynxthecat** [comment]
@moeller0 any idea how to flush a fifo / deal with reads such that they do not block:

```
#!/bin/bash

pipe=/tmp/test
mkfifo $pipe

ping -i 0.1 1.1.1.1 > $pipe&
sleep 1

while read ping_line <$pipe
do
        echo $ping_line

        dd if=$pipe iflag=nonblock of=/dev/null
done
```

**Comment by moeller0** [comment]
Again, why not simply run ping in single-shot mode (`-c 1`) and restart it again?
On an admittedly not too weak dual core arm a9 router I see:
```
rroot@turris:~# time /usr/bin/ping -D -c 1 192.168.42.201
PING 192.168.42.201 (192.168.42.201) 56(84) bytes of data.
[1646741801.236544] 64 bytes from 192.168.42.201: icmp_req=1 ttl=64 time=0.321 ms

--- 192.168.42.201 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.321/0.321/0.321/0.000 ms
real    0m 0.00s
user    0m 0.00s
sys     0m 0.00s
```
so if the rounding is correct, less than 5-10 milliseconds "cost" of setting-up, calling, and executing  ping (to a local target, so we see the rest of pings static cost better) so with a desired interval of 100ms there is no need to keep ping running...

**Comment by lynxthecat** [comment]
Perhaps I should revert to this. But I haven't quite given up yet. 

I think ping can be made to block, then write a line, then block, etc. 

So near, yet so far.

**Comment by lynxthecat** [comment]
Since the solution is beyond me, I have put the questions here:

https://forum.openwrt.org/t/for-bash-experts-pipe-buffering/122119/24

and here:

https://stackoverflow.com/questions/71396520/capture-latest-write-to-file-fifo-buffer-and-then-flush-the-file-fifo-buffer

**Comment by lynxthecat** [comment]
@Marctraider does this result in CPU increasing with time for you:

```
#!/bin/bash

pipe=/tmp/test
mkfifo $pipe

ping -i 0.1 1.1.1.1 > $pipe&

cat $pipe > /dev/null&

cat $pipe | while read line
do
        echo $line
done
```

**Comment by lynxthecat** [comment]
@richb-hanover @Marctraider I have pushed new commit to 'CAKE-autorate' based on the bash named pipe solution - does it resolve the CPU usage issue?

**Comment by Marctraider** [comment]
Look like this fixes it, I see in all situations 2-5% usage at best, both fully loaded and idle. 

Great! I will keep testing upcoming days for oddities but it looks like you nailed it. 👍

**Comment by richb-hanover** [comment]
Alas... Even with this new version, I still see high usage. Here's a Youtube showing a few percent when the router is idle (and not running CAKE-autorate.sh)

Starting it consumes ~100% of the CPU, and the load average keeps creeping up.

https://youtu.be/jqqe4PhySJs

**Comment by Marctraider** [comment]
![image](https://user-images.githubusercontent.com/29001732/157578901-413daa67-82f8-425f-a2d7-c9235fa17b79.png)

A few hours after the script running, doing all sorts of things in the meanwhile including high bandwidth streams (4K 100+Mbps)

**Comment by moeller0** [comment]
> Starting it consumes ~100% of the CPU, and the load average keeps creeping up.

Interesting, it appears mostly to be SIRQ (if I recognized the color of the bars correctly) and does not reflect in a large amount of CPU% assigned to either bash or the ping processes themselves. I wonder whether that is related to the FIFO, or any other things the script might do?

In case you repeat that test, could you also get the output of `tc -s qdisc` while the script is running, as well as the output of `df -h` (to see whether /tmp might be too large). Finally, it would be intersteing ot see a speedtest with the script running... I assume that will be attrocious.

**Comment by lynxthecat** [comment]
Also I have made a few more changes given the outcome of the discussion at: 

https://forum.openwrt.org/t/for-bash-experts-pipe-buffering/122119/

Now the while loop for each reflector actually keeps up with every ping (not every other ping), and so I fear this may actually result in increased CPU usage, but @Marctraider it would be good to verify that the creeping CPU usage effect has still been ameliorated. 

I am hoping there is some low hanging fruit in terms of getting CPU usage down, but I am operating at my limit in terms of bash scripting - it already has quite a few fancy features such as background process management, fifo use, etc. 

Do any of you see any such low hanging fruit offering easy reductions to CPU usage? @dim-geo mysteriously helped out with my original 'ash' script and got CPU usage down, so perhaps he has some ideas for this new bash implementation in the 'CAKE-autorate' branch.

@richb-hanover thanks very much for the kind offer. I am definitely keen to try to optimise this but maybe let's see first if we can get it down with a few easy fixes on the code.

**Comment by Marctraider** [comment]
![image](https://user-images.githubusercontent.com/29001732/157727706-3f0b06ad-aa91-4232-b391-d3256f1286d5.png)

**Comment by lynxthecat** [comment]
@Marctraider I am very grateful for you confirming. How is the performance in terms of rate control for you? For me I am very happy with the way it is handling my CAKE rate (which spans from about 20 to about 70 Mbit/s for me). 

The new version will likely perform slightly better because the ping frequency is higher and also I now interleave pings so they are better spread out. I expect CPU utilisation to increase a little, but hopefully it will remain low.

**Comment by Marctraider** [comment]
You're very welcome.

I haven't done any extensive tweaking and min/maxing but i'm lucky to have a practical scenario where I can literally drop my internet speed at will so I can basically 'simulate' a sudden drop in available bandwidth, without 'switching' connections which is really nice.

So far I'm really happy about its performance and result (so far). Anywhere between 5 and 10% CPU is still acceptable for me so in my book I'm fine with some additional cycles used if that means more optimization. 

As for /tmp, its Debian default (So I assume just disk).  df -h does not indicate a mountpoint directly to /tmp so i assume it just goes under /

```
root@redundant:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           375M  724K  374M   1% /run
/dev/mmcblk0p2   28G  9.4G   17G  37% /
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/mmcblk0p1  511M  3.5M  508M   1% /boot/efi
/dev/sda1       110G   24K  104G   1% /mnt/backup
tmpfs           375M     0  375M   0% /run/user/0

```

As for load, it looks like i see two processes of CAKE-autorate.sh at an average of 1% and 2% continuously. (On baseline 175Mbit qdisc) right after a bandwidth test. Shortly after that (assuming the pings stop) i just see one process at roughly 1-2%.

I see now that after a while the tc qdisc goes to minimum set of 90Mbit, this is correct yes?

**Comment by lynxthecat** [comment]
It would be good to verify /tmp/CAKE-autorate is always on ram for most users. If it would sometimes end up on a disk like an HDD I imagine that might hurt performance a little. 

Concerning minimum yes. It is designed to go to sleep providing the base load is maintained for ping_sleep_thr seconds - it stops the pinger processes and sets bandwidth to minimum (for safety to deal with any step loads) and then when load hits the load threshold it turns the pingers back on, does not change load until next loop and then allows decaying back to base or if load is sustained increasing with the normal set rate for load increase.

The new version handles the fifo buffer slightly differently so I am hoping it is still OK. It also interleaves pings. And on my router I am seeing every ping line captured with 4 reflectors and 0.1s pings, so it looks good. There may be a need to apply a 'dd flush' on the fifo at certain points, but I am not sure yet.

**Comment by lynxthecat** [comment]
Can you see any optimizations for this loop:

https://github.com/lynxthecat/sqm-autorate/blob/CAKE-autorate/monitor_reflector_path.sh#L52

Since this is where a lot of the processing is done.

**Comment by lynxthecat** [comment]
By the way:

`echo $(date +%s.%N) $ping_line`

here:

https://github.com/lynxthecat/sqm-autorate/blob/CAKE-autorate/monitor_reflector_path.sh#L73

Can be used to verify that the pings are being processed in the right way by inspecting the ping lines and comparing timestamps against the system timestamps.

**Comment by Marctraider** [comment]
```
root@redundant:~# ps
    PID TTY          TIME CMD
 695957 pts/1    00:00:00 bash
 716593 pts/1    00:00:00 ps
root@redundant:~#

```

No results for pings, but that is not right as i can clearly see the pings going in 'top', also my own pings from another script are running. But I'm sure it works fine, i could indeed check with tcpdump but there's also other pings to the same gateway ongoing at the moment lol.

**Comment by richb-hanover** [comment]
Field report for https://github.com/lynxthecat/CAKE-autorate/commit/6069321f5cbeaf577e42b42a6768c1335fefeb3c on my Archer C7v2...

Using `reflector_ping_interval=0.1`:
* CPU usage 75% +/- 5% - it is very stable
* Load average settled to 1.2
* Running `betterspeedtest.sh` made CPU spike to 100% and Load Average go to 2.0+

Using `reflector_ping_interval=0.2`:
* CPU usage about 40%
* Load Average about 0.8
* Running `betterspeedtest.sh` made CPU spike to 85-95% during download and Load Average go to 2.0+

Also: During the _download_ phase of `betterspeedtest.sh` the script continually write lines like this, over and over...
```
WARNING: encountered response from [ 8.8.8.8 ] that is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.4.4 ] that is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] that is > 500ms old. Skipping.
WARNING: encountered response from [ 1.1.1.1 ] that is > 500ms old. Skipping.
```
This did _not_ happen during the upload phase of the speedtest

**Comment by lynxthecat** [comment]
Thank you for testing @richb-hanover. The skipping occurs when the main processing loop cannot keep up with the rate of incoming data. It seems like with the Archer C7 even just ordinary traffic at your line rate causes huge CPU spikes. Did this also occur with the ping interval set to 0.2? How about reducing the reflectors to just 2 and use 0.5? 

Do you have a sense of how these different scripts you are testing are performing in terms of controlling CAKE bandwidth (i.e. offering bandwidth when needed but preventing significant bufferbloat?).

**Comment by richb-hanover** [comment]
> Thank you for testing @richb-hanover. The skipping occurs when the main processing loop cannot keep up with the rate of incoming data. It seems like with the Archer C7 even just ordinary traffic at your line rate causes huge CPU spikes. 

I'm not sure that's the explanation. I changed the code to display $t_start and $other_value, and got these results:

```
WARNING: encountered response from [ 1.1.1.1 ] 1647651329344444 1647651328837871 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.8.8 ] 1647651329425467 1647651328909500 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.8.8 ] 1647651329628267 1647651329110978 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647651329815810 1647651329279158 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.8.8 ] 1647651329821885 1647651329309592 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.1.1.1 ] 1647651329960633 1647651329436894 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.8.8 ] 1647651330065726 1647651329515942 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.4.4 ] 1647651330078407 1647651329572759 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647651330201532 1647651329677802 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.4.4 ] 1647651330924455 1647651330375886 is > 500ms old. Skipping.
```

The differences _are_ greater than 500,000, but slightly. However, I never see 500+msec lag in the router - the added latency is generally 5-10 msec. 

NB If I create a two-second blast of data, 10 lines of _500 ms old. Skipping_ get generated when the ping interval is 0.2.

> Did this also occur with the ping interval set to 0.2? How about reducing the reflectors to just 2 and use 0.5?

No. Either setting ping interval to 0.2 or using only two reflectors doesn't generate those messages.

Actually, not quite true. Sometimes, either of those combinations causes a single _Skipping_ message to be generated.

> Do you have a sense of how these different scripts you are testing are performing in terms of controlling CAKE bandwidth (i.e. offering bandwidth when needed but preventing significant bufferbloat?).

I can't say. (I have fixed speed at 25mbps - the latency always stays between 7 & 15 msec)

**Comment by lynxthecat** [comment]
Thanks @richb-hanover. There is a glitch here it seems. Perhaps I need to flock the writes.

**Comment by moeller0** [comment]
Mmmh, if you meed flock your wroters will spparently in a race to write and flock usage then can result in out of order writing, so read data needs to be sorted by timestamp by the reader....

**Comment by lynxthecat** [comment]
Actually from testing I am not seeing corruption on the writes but I am seeing some oddity with multiple instances of iputils-ping as posted here:

https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/108848/2556?u=lynx

@richb-hanover I wonder if you could post the data you have in your Excel for me to look at?

Not sure if this is the same issue I am seeing or an unrelated issue.

**Comment by richb-hanover** [comment]
I should have said: the raw data came from the lines I posted in the previous message.

**Comment by richb-hanover** [comment]
I'm not sure what you mean by "flock the writes". That said, I wonder whether it's possible to write the start time as data in the ping packet, and then retrieve it from the response packet...

PS The updated `...Skipping...` line is:
```
((($t_start - "${timestamp//[[\[\].]}")>500000)) && echo "WARNING: encountered response from [" $reflector "] $t_start "${timestamp//[[\[\].]}" is > 500ms old. Skipping." && continue
```

**Comment by lynxthecat** [comment]
@richb-hanover is this just after a period of inactivity? Because the pingers are put to sleep after 60s of inactivity and when they are woken up the skipping flushes out some old data, if that makes sense. Or do you see it in general? 

It could well just be that it is normal/expected behaviour because the processing rate is not keeping up with the incoming data and so it has to skip old values.

**Comment by richb-hanover** [comment]
> @richb-hanover is this just after a period of inactivity? Because the pingers are put to sleep after 60s of inactivity and when they are woken up the skipping flushes out some old data on resume, if that makes sense. Or do you see it in general?

That's a good description of the algorithm. I don't think it quite matches my observations. Here's my test process:

- `bash CAKE-autorate.sh` - no output lines seen
- (immediately - within 10 seconds) switch to another window to look at `htop` - see reasonable CPU/Load Average (as reported earlier)
- (immediately - within 10 seconds) switch to a third window and run `betterspeedtest.sh` - the ...Skipping... messages come out almost immediately (Hmmm... actually, about 1 or 2 seconds) after the download phase starts
- The ...Skipping... messages stop almost immediately (within a second) of the speed test printing download stats and starting the upload phase.

Here is the latest test output:
```
WARNING: encountered response from [ 8.8.4.4 ] 1647697141585781 1647697141081998 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.1.1.1 ] 1647697141758522 1647697141228268 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647697141853458 1647697141333720 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.4.4 ] 1647697142013683 1647697141483457 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.8.8 ] 1647697142123925 1647697141598919 is > 500ms old. Skipping.
WARNING: encountered response from [ 8.8.4.4 ] 1647697142234548 1647697141685495 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647697142246598 1647697141736935 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.1.1.1 ] 1647697142345599 1647697141830188 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647697142468277 1647697141936564 is > 500ms old. Skipping.
WARNING: encountered response from [ 1.0.0.1 ] 1647697142644847 1647697142137290 is > 500ms old. Skipping.
```

**Comment by lynxthecat** [comment]
I believe this is because when you run betterspeedtest.sh your CPU utilisation shoots up and there are not sufficient spare cycles to keep up with the 40Hz processing of incoming ping results, necessitating skipping.

**Comment by moeller0** [comment]
> * (immediately - within 10 seconds) switch to a third window and run `betterspeedtest.sh` - the ...Skipping... messages come out almost immediately (Hmmm... actually, about 1 or 2 seconds) after the download phase starts

I agree with @lynxthecat running netperf on the router, especially an old one like the C7 is asking for CPU overload. It can be seen as a stress test, but IMHO it is harsh to expect hardware that old to deal with both too high an autorate sample rate (40Hz) and the additional load of sourcing/sinking speedtest packets...

**Comment by richb-hanover** [comment]
OK. That sounds right. To confirm, I will run the speed test on my laptop via wifi (so the data passes through the router, instead of running the test _on_ the router) and report back. 

PS You asked this a while back but I never responded: I also see high CPU use using the Lua implementation from perhaps a week ago. Here's the report from that repo... https://github.com/sqm-autorate/sqm-autorate/issues/147

**Comment by moeller0** [comment]
> I will run the speed test on my laptop via wifi (so the data passes through the router, instead of running the test _on_ the router) and report back.

If you could hook up the laptop via ethernet first that would help, as wifi processing puts additional load on the router. Yes, finally this needs to work over wifi, but for debugging/understanding it might make sense to start with wired, no?

**Comment by moeller0** [comment]
Mmmh, if you meed flock your wroters will spparently in a race to write and flock usage then can result in out of order writing, so read data needs to be sorted by timestamp by the reader....

**Comment by lynxthecat** [comment]
Don't think I need flock. Seems to be working just fine without. So I guess the writes are all atomic.

**Comment by lynxthecat** [comment]
After having implemented a few performance enhancements, here is what I see on my RT3200 now at 40Hz:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/10721999/159175659-4d4d98ce-a713-4f6c-a532-d4f1144a0ae6.png">

**Comment by Marctraider** [comment]
@lynxthecat Testing new script now, with very low intervals. I see the config script got a nice rehaul, and you seem to have automated the amount of deflectors depending on how much you fill into the reflector ip field. (I think?)

Is it also possible to have a icmp payload option to reduce that (For whoever is willing?) to conserve some bandwidth?

**Comment by Marctraider** [comment]
Sufficed to say, with reflector_ping_interval=0.015 # (seconds), and icmp payload on 16KB+8KB (icmp header) the script works extremely well.

![image](https://user-images.githubusercontent.com/29001732/159824155-d4abf076-1870-4b4b-8119-978e557c00fe.png)

**Comment by lynxthecat** [comment]
@Marctraider so far so good, I am pretty happy with all of this. And especially that your removing the fast line, resulting in the usable capacity dropping, results in next to no latency budge. I think this means the script is behaving correctly. 

There are still a couple of outstanding CPU gains to work on. For example I discovered recently that the $(printf) call to convert RTTs from float to integer in microseconds is costly. I am going to replace that with bash pattern matching, and just use one match with multiple capture groups rather than two separate matches for sequence and RTT as I do presently. This should reduce the CPU usage per reflector a little. But since it's per reflector, that will add up.

Curious about CPU load jumping up so much from: reflector_ping_interval=0.02 to 0.01. These are seriously low numbers. Bear in mind that the main loop has to process every ping result line. That is 100Hz per reflector at 0.01. I wonder what is killing the CPU so much in jumping from 0.02 to 0.01. Perhaps the 'tc qdisc change' calls? Could you try commenting those out with 0.01 to see if that is the culprit. Or perhaps it is just the common fifo writing / reading that grinds to a halt at a certain rate.

@moeller0 any thoughts on the above from networking perspective since this is straying beyond my area of expertise?

Regarding:

> Is it also possible to have a icmp payload option to reduce that (For whoever is willing?) to conserve some extra bandwidth?

Yes no problem I will just add this as a user-configuration option. 

@moeller0 what is the optimum for the general case and for @Marctraider?

**Comment by richb-hanover** [comment]
These are interesting observations, and a couple follow-on thoughts came to mind.

* re: printf() I wondered about, and am not surprised to hear the printf() calls are expensive. Might it be helpful to wrap those calls in an if statement so they're not evaluated at all if debugging/printing isn't turned on?

* Am I correct that you're talking about 2 msec vs 1 msec polling and its effect on CPU usage? A frequent observation in queuing theory (like networking) is that there's a knee in the performance curve where delay increases abruptly as you increase traffic. In this case, I suspect the fixed overhead of some operation begins to dominate, and the processor spends "all its time" on those fixed, unavoidable overheads. 

* I had another thought about increased ping rates. I have a data plan for my LTE cellular modem. In the US, it's brutally expensive: $20/month for 2GBytes; $40/month for 10GBytes. (At least my plan is called "Unlimited" - if I exceed the threshold, they permit something like 100kbps so I can make voice calls, read email, etc.) In any event, can we make predictions about the data consumed by ping traffic? (I like the fact that the algorithm only starts pinging when there's interesting traffic, so that will cut it down.)

* I _still_ wonder how we could devise tests to characterize variations in speed for our various underlying links. That could inform our choice of ping rates. How could we determine a "rate of change", possibly measured in percent change per second or per 10 seconds. I believe that Cable Modems have a daily variation (slow after supper, fast in the wee hours). But how much variation do they exhibit moment to moment (or minute by minute)?  Mr Nyquist suggests there is no value in sampling more than twice that fast...

* re: User options. I dislike them. The seem easy to implement, but... They're extra code that needs to be tested in combination with every other option. They _still_ can break. They need to be documented. People need to understand that documentation, use the option correctly. But most importantly, a lot of times, the algorithm can "do the right thing" without asking the human, so it's worth experimenting with a couple approaches and simply picking the best one. (In the case of the icmp payload, is there ever a case in production where less bandwidth would be a bad choice?)

Thanks for listening!

**Comment by moeller0** [comment]
> $(printf)

Are you sure it is printf or the sub-shell invocation? If the latter you culd try `printf -v my_printfed_var` to assign the value to a variable without the subshell?



> That is 100Hz per reflector at 0.01.

Many reflectors are rate limited, querying individually reflectors is asking for trouble.... Don't do that...



> Perhaps the 'tc qdisc change' calls?

Aren't these guarded by the refractory period after a change?



> Is it also possible to have a icmp payload option to reduce that (For whoever is willing?) to conserve some extra bandwidth?

For this keep in mind ethernet's minimal packet size, so beow a certain value reducing the packet size will not reduce the bandwidth... also the ICMP size needs to be large enough to fit the timespec of the sender (IIRC that is larger on 64bit systems than on 32bit systems)...



> @moeller0 what would you say is the optimum for the general case and for @Marctraider?

I would assume that the default size is what most code out there is likely to be tested with and tuned for, so I would tend to stick to that as the default... I would, however, not ping at 100Hz which also will reduce the load from the ping traffic....



> * re: printf() I wondered about, and am not surprised to hear the printf() calls are expensive. Might it be helpful to wrap those calls in an if statement so they're not evaluated at all if debugging/printing isn't turned on?

+1, that sounds sane independent of the printf cost....



> * Am I correct that you're talking about 2 msec vs 1 msec polling and its effect on CPU usage? A frequent observation in queuing theory (like networking) is that there's a knee in the performance curve where delay increases abruptly as you increase traffic. In this case, I suspect the fixed overhead of some operation begins to dominate, and the processor spends "all its time" on those fixed, unavoidable overheads.

It makes oddles of sense to test how well/tight the experience with this script depends on the RTT sampling rate... My assumption is that probably 10-20Hz should be sufficient and 100Hz is not going to be sufficiently better to justify the noticeable increase in cost.... but I have not tested that so ...



> * (I like the fact that the algorithm only starts pinging when there's interesting traffic, so that will cut it down.)

The cost of that however is that the baseline estimates get stale.... on a volume limited link still better than constant pinging, but on a truly unlimited link not so much (I would peferr to simply thing the pings out to 1/sec, then 1/minute). Estimating the load is not that hard multiply the ping size by its rate and report that to the user.



> * re: User options. I dislike them. The seem easy to implement, but... They're extra code that needs to be tested in combination with every other option. They _still_ can break. They need to be documented. People need to understand that documentation, use the option correctly. But most importantly, a lot of times, the algorithm can "do the right thing" without asking the human, so it's worth experimenting with a couple approaches and simply picking the best one. (In the case of the icmp payload, is there ever a case in production where less bandwidth would be a bad choice?)

Yes, if either the reflector puts the packet into a slow path or drops unusual packet sizes completely or when the size is to small to fit the timespec as in that case the ping will not return an RTT...

**Comment by lynxthecat** [comment]
> Perhaps the 'tc qdisc change' calls?
> 
> Aren't these guarded by the refractory period after a change?

I need to have another think about how I handle refractory periods. At the moment I have:

```
 		# in case of supra-threshold OWD spikes decrease the rate providing not inside bufferbloat refractory period
		bufferbloat)
			(( $t_next_rate > ($t_last_bufferbloat+$bufferbloat_refractory_period) )) && 
				cur_rate=$(( ($rate*$rate_adjust_bufferbloat)/1000 )) && 
				t_last_bufferbloat=${EPOCHREALTIME/./}
			;;
           	# ... otherwise determine whether to increase or decrease the rate in dependence on load
            	# high load, so increase rate providing not inside bufferbloat refractory period 
		high_load)	
			(( $t_next_rate > ($t_last_bufferbloat+$bufferbloat_refractory_period) )) && 
				cur_rate=$(( ($cur_rate*$rate_adjust_load_high)/1000 ))
			;;
		# low load, so determine whether to decay down towards base rate, decay up towards base rate, or set as base rate
		low_load)
			if (($t_next_rate > ($t_last_decay+$decay_refractory_period) )); then
```

So an increase in load without bufferbloat is not subject to any refractory period. Should it be? My logic of not having this is that as you said earlier @moeller0 it is limited by the rate being > the high rate threshold (e.g. 75%).

**Comment by lynxthecat** [comment]
@moeller0 this gives 1% per reflector rather than 2% per reflector in top on my RT3200:

```
# ping reflector, maintain baseline and output deltas to a common fifo
monitor_reflector_path()
{
        local reflector=$1
        local rtt_baseline=$2

        while read -r  timestamp _ _ _ reflector seq_rtt
        do
                [[ $seq_rtt =~ icmp_seq=([0-9]*).*time=([0-9]*)[.]*([0-9]*)[[:space:]]ms ]];

                # If output line of ping does not contain any RTT then skip onto the next one
                [ -z ${BASH_REMATCH[2]} ] && continue

                rtt=$((${BASH_REMATCH[2]}*1000))

                # If there is a fractional component then add it on
                [ -z ${BASH_REMATCH[3]} ] && ((rtt+=100*${BASH_REMATCH[3]}))

                seq=${BASH_REMATCH[1]}

                reflector=${reflector//:/}

                rtt_delta=$(( $rtt-$rtt_baseline ))

                alpha=$alpha_baseline_decrease
                (( $rtt_delta >=0 )) && alpha=$alpha_baseline_increase

                rtt_baseline=$(( ( (1000-$alpha)*$rtt_baseline+$alpha*$rtt )/1000 ))

                echo $timestamp $reflector $seq $rtt_baseline $rtt $rtt_delta > /tmp/CAKE-autorate/ping_fifo
        done< <(ping -D -i $reflector_ping_interval $reflector & echo $! >/tmp/CAKE-autorate/${reflector}_ping_pid)
}
```

What do you think? I think this is perhaps as good as it gets for the per-reflector process.

**Comment by Marctraider** [comment]
@lynxthecat So far 0.015s is optimal i think. I dont think i wanna go any lower wasting more energy than necessary. 10% total of script and children processes should be the max acceptable under load.

I already tried disable debugging again to see if 0.01 would alleviate the sudden massive ping cpu usage, but im pretty sure that didnt fix it.

Ofcourse my own reflector can be icmp spammed to the limits of its 1/1Gbit full duplex 99,99% uptime vps :P

So tweaking wise, i would with the current usage of the total package not even want to go lower than 0.01, but still curious why this happens.

I can try the fping method.

**Comment by moeller0** [comment]
> What do you think?

This is ugly as hell.... I guess if this is really only half as costly as doing `printf -v rtt ...` might be worth it, but I feel dirty reading this ;)

Also I really think the rtt should be split into ul_delay and dl_delay (as well as baseline and delta) and the record should be ended wit a repetition of timestamp as an indicator for potential partial overwrites....



> @lynxthecat So far 0.015s is optimal i think given the restrains that the 'bug' introduces. I dont think i wanna go any lower wasting more energy than necessary. 10% total of script and children processes should be the max acceptable under load.

The question is is 15ms noticeably better than 30ms?



> In the fortunate case thst the script might become even more efficient, i wouldnt mind going 0.01 or even 0.005.

But why? There are going to be diminishing returns on pushing this ever lower, the question should be how large can this be made without control loop tightness suffering. So the optimization goal here should be as large as possible ;)






> Another good question might be, since I control my own endpoint, would it benefit me to apply qos to server side instead?

Yes egress shaping tends to be simpler so shaping on the VPS for your download direction seems sane, but youmay  need to potentially reduce the ICMP probe rate a bit...



> What about ECN (BBR) on both sides?

That is orthogonal to getting the shaper set correctly, ECN can help but not in fighting bufferbloat (only i that congestion signaling reaches the endpoints slightly faster via ECN instead of dropping, as after a dropped packet two more packets need to arrive at the receiver before that trigger a 2 dupACK response, while a single CE mark will achieve similar results)

**Comment by Marctraider** [comment]
Hey you pinged the wrong person but thats fine, I'm sure at some point there will be diminishing returns, but I haven't gone through testing this yet. Would be easier if I could create my own graphs based on tests but I don't really have an infrastructure going for that at the moment.

Frankly the question for me would be, whats the optimal lower interval rate versus bandwidth (With lower ICMP payload) and the fact that my line is reasonably wide when it comes to bandwidth, and bandwidth limitations are of no concern, the only other aspect is cpu load itself.

**Comment by moeller0** [comment]
> As for @lynxthecat, I'll asusume he'll want to figure out whats causing an increase of CPU from single digits to 50+% on the ping process whenever interval drops from 0.02 (or even 0.15) to 0.01. Because it doesn't make much sense.

That could be anything... wild guess: the ping binary might switch between sleep and busy polling depending on the requested interval (as short sleeps are notoriously imprecise)...

**Comment by lynxthecat** [comment]
It looks like you may be right @moeller0:

`root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 100 -i 0.1 192.168.1.2 > /dev/null
real    0m 9.94s
user    0m 0.00s
sys     0m 0.03s
root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 1000 -i 0.01 192.168.1.2 > /dev/null
real    0m 10.03s
user    0m 2.67s
sys     0m 5.89s`

**Comment by moeller0** [comment]
Ah, there is also the thing that `-i < 0.2` requires super user privileges IIRC, so there might be extra checks involved?

**Comment by Marctraider** [comment]
> It looks like you may be right @moeller0:
> 
> ```
> root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 1000 -i 0.02 192.168.1.2 > /dev/null
> real    0m 20.62s
> user    0m 0.06s
> sys     0m 0.21s
> root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 1000 -i 0.01 192.168.1.2 > /dev/null
> real    0m 10.14s
> user    0m 1.95s
> sys     0m 4.75s
> ```
> 
> Here is the same with fping:
> 
> ```
> root@OpenWrt:~# time fping -c 1000 -p 20 192.168.1.2 > /dev/null
> 
> 192.168.1.2 : xmt/rcv/%loss = 1000/1000/0%, min/avg/max = 0.960/2.08/8.84
> real    0m 19.98s
> user    0m 0.31s
> sys     0m 0.00s
> root@OpenWrt:~# time fping -c 1000 -p 10 192.168.1.2 > /dev/null
> 
> 192.168.1.2 : xmt/rcv/%loss = 1000/1000/0%, min/avg/max = 1.000/2.05/6.99
> real    0m 10.11s
> user    0m 0.11s
> sys     0m 0.18s
> ```

I will try the same on my system.

**Comment by lynxthecat** [comment]
Note to self - I need to implement this proposal:

> What I would like to see is for all CPUs/HT-siblings 100-%idle... loadavg is not the right measure here...
> I would use the cpuN lines from cat /proc/stat
> 
> ```
> root@turris:~# cat /proc/stat 
> cpu  5909064 26936 1697407 210303430 1809247 0 1440728 0 0 0
> cpu0 3066461 13859 842812 105338697 943297 0 388277 0 0 0
> cpu1 2842603 13077 854595 104964733 865950 0 1052451 0 0 0
> intr 1361849891 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 718231763 0 0 111179 22 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20486552 15267694 147090191 0 0 0 0 0 2811330 0 14517374 0 2 2 0 0 0 0 0 0 0 40 0 0 4 0 3 33 0 0 0 0 0 0 0 0 0 0 0 1 0 113784447 140749112
> ctxt 1038967495
> btime 1647964976
> processes 2324144
> procs_running 1
> procs_blocked 0
> softirq 1549519881 0 187760591 164873342 579513036 5016228 0 297775348 214348509 0 100232827
> ```
> 
> for that purpose, and I would ignore the governor/power scheduler effects... (or I would try to also add information about the CPUs frequencies, but that gets approximate pretty quickly so I think ignoring that is just fine)...

https://forum.openwrt.org/t/bufferbloat-continuous-measurement-script/124217/12?u=lynx

**Comment by Marctraider** [comment]
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 188803 root      20   0    6992   3592   3136 R  14.0   0.1   0:01.58 CAKE-autorate.s
 188823 root      20   0    7280   2728   2000 S   5.3   0.1   0:00.62 CAKE-autorate.s
    484 root      20   0  708040  34036   8680 S   4.3   0.9  90:24.92 engarde-client
    806 root      20   0  103824   9524   5036 S   0.7   0.2   1:23.56 dhcpd
 186648 root      20   0       0      0      0 I   0.7   0.0   0:00.14 kworker/1:3-wg-crypt-wg0
 188826 root      20   0    4200    732    616 S   0.7   0.0   0:00.09 ping

```

Latest main branch, interval of 0.005.

```
output_processing_stats=1 # enable (1) or disable (0) output monitoring lines showing processing stats
output_cake_changes=0     # enable (1) or disable (0) output monitoring lines showing cake bandwidth changes
debug=0                   # enable (1) or disable (0) out of debug lines

# *** STANDARD CONFIGURATION OPTIONS ***

ul_if=wg0        # upload interface
dl_if=ifb4wg0 # download interface

reflector_ping_interval=0.005 # (seconds, e.g. 0.2s or 2s)

# list of reflectors to use
reflectors=("10.0.0.1")

delay_thr=15 # extent of RTT increase to classify as a delay

min_dl_shaper_rate=90000  # minimum bandwidth for download (Kbit/s)
base_dl_shaper_rate=175000 # steady state bandwidth for download (Kbit/s)
max_dl_shaper_rate=200000  # maximum bandwidth for download (Kbit/s)

min_ul_shaper_rate=20000  # minimum bandwidth for upload (Kbit/s)
base_ul_shaper_rate=100000 # steady state bandwidth for upload (KBit/s)
max_ul_shaper_rate=120000  # maximum bandwidth for upload (Kbit/s)

# sleep functionality saves unecessary pings and CPU cycles by
# pausing all active pingers when connection is not in active use
enable_sleep_function=1 # enable (1) or disable (0) sleep functonality
connection_active_thr=500   # threshold in Kbit/s below which dl/ul is considered idle
sustained_idle_sleep_thr=60 # time threshold to put pingers to sleep on sustained dl/ul achieved rate < idle_thr (seconds)

# *** ADVANCED CONFIGURATION OPTIONS ***

monitor_achieved_rates_interval=100 # (milliseconds)

bufferbloat_detection_window=4  # number of delay samples to retain in detection window
bufferbloat_detection_thr=1     # number of delayed samples for bufferbloat detection

alpha_baseline_increase=0.001 # how rapidly baseline RTT is allowed to increase
alpha_baseline_decrease=0.9   # how rapidly baseline RTT is allowed to decrease

achieved_rate_adjust_bufferbloat=0.9 # how rapidly to reduce achieved rate upon detection of bufferbloat
shaper_rate_adjust_bufferbloat=0.9   # how rapidly to reduce shaper rate upon detection of bufferbloat
shaper_rate_adjust_load_high=1.01    # how rapidly to increase shaper rate upon high load detected
shaper_rate_adjust_load_low=0.98     # how rapidly to return to base shaper rate upon low load detected

medium_load_thr=0.25 # % of currently set bandwidth for detecting medium load
high_load_thr=0.75   # % of currently set bandwidth for detecting high load

bufferbloat_refractory_period=300 # (milliseconds)
decay_refractory_period=1000 # (milliseconds)

```

Not sure what changed? Haven't been into the loop much, i did update my kernel and debian packages recently. (Doubt its the cause tho).

**Comment by moeller0** [comment]
> Just to clear things up; Having other ping processes from other scripts running in the background should be of no concern right?

Well, you only have that many CPUs and CPU cycles available, the more processes compete for the CPUs the more waiting will happen, if ping resorts to busy wait that might cause such issues I could make myself believe ;)

**Comment by lynxthecat** [comment]
> It looks like you may be right @moeller0:
> 
> root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 1000 -i 0.02 192.168.1.2 > /dev/null
> real    0m 20.62s
> user    0m 0.06s
> sys     0m 0.21s
> root@OpenWrt:~/CAKE-autorate# time /usr/bin/ping -c 1000 -i 0.01 192.168.1.2 > /dev/null
> real    0m 10.14s
> user    0m 1.95s
> sys     0m 4.75s
> Here is the same with fping:
> 
> root@OpenWrt:~# time fping -c 1000 -p 20 192.168.1.2 > /dev/null
> 
> 192.168.1.2 : xmt/rcv/%loss = 1000/1000/0%, min/avg/max = 0.960/2.08/8.84
> real    0m 19.98s
> user    0m 0.31s
> sys     0m 0.00s
> root@OpenWrt:~# time fping -c 1000 -p 10 192.168.1.2 > /dev/null
> 
> 192.168.1.2 : xmt/rcv/%loss = 1000/1000/0%, min/avg/max = 1.000/2.05/6.99
> real    0m 10.11s
> user    0m 0.11s
> sys     0m 0.18s
> I will try the same on my system.

Did you try this though? I think it's just an oddidity in iputils-ping?

**Comment by lynxthecat** [comment]
If it helps then you can easily make the substitution in the main branch. 

Actually the main branch has major changes in it not present in the fping branch that I think you might benefit from. For example I have now set it up so that the rx and tx loads are monitored in an asynchronous fashion. This should help you because I don't think in your case of extreme high pings we should be working with loads calculated between pings. Does this make sense?

**Comment by Marctraider** [comment]
@lynxthecat Hey there! Sorry I've been AWOL due to IRL stuff!

The plan was to run the script 24/7 but upon encountering some weird behavior I have not yet managed to extrapolate, I've delayed the integration of the script into my network infrastructure.

The problem was as follows: Upon activating the script (And seeminly seems to function well) I got erratic ping spikes from my other scripts (The basic interface logging ping instances) which started jumping around for no good reason, while the connection is mostly IDLE.

I'm not sure why. Let me test again and get back to you (In case i might be able to solve it)

**Comment by lynxthecat** [comment]
Thanks. Your feedback is appreciated because it helps to robustify this script (which seems to have received a fair amount of attention).

**Comment by Marctraider** [comment]
Currently one of my links appear deteriorated, I want to test in a different setting so I'll check back tomorrow. Ugh!

**Comment by Marctraider** [comment]
@lynxthecat 

The script works fine now, also no idle i see now weird behavior i was seeing a while back. CPU usage is very nice as well.

Just some remaining questions/features:

- Possibility to set ICMP payload size as an option in the config.sh
- Should I adjust any of the reflector misbehavior configuration on a self-owned reliable reflector?
- Once on a blue moon I reboot my dedicated server endpoint (Updates, or new kernel), i see that the script stops pinging (from the router end) when the reflector is no longer pingable. Any way to make the script automatically go again once pinging can continue?

Otherwise, no issues found!

**Comment by lynxthecat** [comment]
If you just set one reflector in the array it will simply hit this line:

https://github.com/lynxthecat/CAKE-autorate/blob/main/CAKE-autorate.sh#L282

And keep using that reflector. I don't think you would need to adjust anything else. 

I will add in the idea about the ICMP payload size. Can you let me know what you use and why you changed it?

**Comment by Marctraider** [comment]
Pretty settled indeed!

The reason I can think of is bandwidth preservation and simply efficiency. (56 bytes seems default, can easily drop it down to 20 i believe which is more than two times less bandwidth wasted)

**Comment by lynxthecat** [comment]
Seems to make sense to me.

**Comment by Marctraider** [comment]
Hrm, frankly I had not thought of that. 

I will do some wireshark/tcpdump tests later on this.

**Comment by Marctraider** [comment]
Well after having some big networking issues, namely my dedicated server's network card seem to start crapping out on me (they finally fixed it yesterday but I've been trying to debug my poor connection for days now) 

I've been reworking my whole infrastructure and once that's done I will do some retesting with the script as it was not behaving properly. Ugh!

**Comment by Marctraider** [comment]
I have another issue which requires resolving, before I can make the script behave well.

Currently for unexplained reasons, my tunnel (wg) gets 'choked' by 10 to 20 Mbit regardless of what bandwidth limit I set on my cake qdisc, even before the script is involved. My total bandwidth with iPerf3 is 180Mbit but once I apply SQM to the interface (Even with a cap of 250Mbit or higher) the total bandwidth gets capped to around 150~Mbit/s.

Also suspect the tunnel is slightly deteriorated. 

Unknown why this happens at present moment!

**Comment by lynxthecat** [comment]
Thanks for the update. Any further developments on whether lowering packet size makes a tangible difference?

**Comment by Marctraider** [comment]
No I think I'll leave that request for now. I'm not experienced enough with inner and outer layer packets to get a definitive answer to this one.

Bandwidth usage shouldn't really be much of a problem these days, and the sleep function should solve exactly that.

Thanks though!

**Comment by lynxthecat** [comment]
I think CPU usage has been brought down to acceptably low levels and significant further improvement would require switching from bash.  But anyone reading this feel free to reopen if you can see any further area for improvement.

**Comment by lynxthecat** [comment]
@Marctraider circling back to:

https://github.com/lynxthecat/cake-autorate/issues/17#issuecomment-1095143262

you may wish to try out the new stall-detection-fping branch since the switch to fping may well resolve your high frequency timing issue.

**Comment by richb-hanover** [comment]
> I can plot your data in excel if you upload the log file.

I would be pleased to see a description (perhaps in a new page in the Github repo) that:

1. Describes the plots and all the variables that are shown there. There are a zillion lines shown, and it's hard to get a handle on them. (I felt the urge to do this for the RRUL test - see https://www.bufferbloat.net/projects/bloat/wiki/RRUL_Chart_Explanation/)
2. Describes the procedure for creating the plots in Excel, so that people can do it for themselves

Thanks!

**Comment by lynxthecat** [comment]
Good point, will do. Yes the readme needs a lot of work with all these changes. And I will factor this in too.

**Comment by richb-hanover** [comment]
I would factor out this discussion (creating/interpreting charts) into a separate document. It's real special-purpose knowledge, and I woudn't want to frighten people away because creating the charts looks forbidding...
